### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by piekie** [piekie/Int-To-String-And-Reversive#1]
- [x] make this to work
- [ ] add overflow functionality
- [ ] add validating of input 
- [ ] add wiki
